FORMAT: 1A
HOST: https://5p7z1m4of5.execute-api.ap-southeast-2.amazonaws.com/prod/

# Serverless-es6-dynamodb-webapi

A simple web API powered by Serverless (Node.js) and DynamoDB, intended as a starting point for Serverless web APIs. This project uses serverless-webpack with Babel to compile handler functions written in ES6.

# Group Items
Operations to retrieve/update Items.

## Items [/items]

### Get all Items [GET]

+ Response 200 (application/json; charset=utf-8)

    + Attributes

        + items (array[FullItem])

### Create an Item [POST]

+ Request (application/json; charset=utf-8)
    + Body

            {
                "name" : "James Bond"
            }

+ Response 200 (application/json; charset=utf-8)

    + Attributes (FullItem)

### Edit an Item [PATCH /items/{id}]

+ Parameters
    + id: `a34839f1-4896-4770-99fc-b9c8c2add08d` (string, required)

+ Request (application/json; charset=utf-8)
    + Body

            {
                "name" : "James Bond"
            }

+ Response 200 (application/json; charset=utf-8)

    + Attributes (UpdatedItem)

### Delete an Item [DELETE /items/{id}]

+ Parameters
    + id: `a34839f1-4896-4770-99fc-b9c8c2add08d` (string, required)

+ Response 200


## Data Structures

### FullItem (object)
+ id: `a34839f1-4896-4770-99fc-b9c8c2add08d` (string, required)
+ name: James Bond (string, required)
+ createdUtc: `2016-10-17T00:00:00.000Z` (string, required)

### UpdatedItem (object)
+ id: `a34839f1-4896-4770-99fc-b9c8c2add08d` (string, required)
+ name: Jim Bond (string, required)
