# All commands below are run from root directory of repository by CodeBuild
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-southeast-4"
    REMOTE_STATE_BUCKET: "jch254-terraform-remote-state"
    TF_STATE_KEY: "serverless-node-dynamodb-api"
  parameter-store:
    AUTH0_CLIENT_SECRET: "/serverless-node-dynamodb-api/auth0-client-secret"
    CLOUDFLARE_API_TOKEN: "/serverless-node-dynamodb-api/cloudflare-api-token"

phases:
  install:
    commands:
      - echo Setting up Terraform plugin cache...
      - export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
      - mkdir -p "$TF_PLUGIN_CACHE_DIR"
      # Workaround until CodeBuild/CodePipeline retains file permissions
      - find ./infrastructure -name "*.bash" -exec chmod +x {} \;
      - echo Installing Node dependencies...
      - corepack enable
      - corepack prepare pnpm@9.15.9 --activate
      - pnpm config set store-dir /root/.pnpm-store
      - ./infrastructure/install.bash

  build:
    commands:
      - ./infrastructure/deploy-infrastructure.bash
      - ./infrastructure/deploy-serverless.bash

cache:
  paths:
    - "infrastructure/terraform/.terraform/modules/**/*"
    - "infrastructure/terraform/.terraform/plugins/**/*"
    - "/root/.terraform.d/plugin-cache/**/*"
    - "/root/.pnpm-store/**/*"
